 all: main.cpp Track.cpp Session.cpp Conference.cpp SessionOrganizer.cpp
	  g++ -o main main.cpp Track.cpp Session.cpp Conference.cpp SessionOrganizer.cpp
		./main sample_problems/inputfile1.txt sampleoutputs/outputfile1.txt
		cat sampleoutputs/outputfile1.txt
		./main sample_problems/inputfile2.txt sampleoutputs/outputfile1.txt
		cat sampleoutputs/outputfile1.txt
		./main sample_problems/inputfile3.txt sampleoutputs/outputfile1.txt
		cat sampleoutputs/outputfile1.txt
		./main sample_problems/test_mayank.txt sampleoutputs/outputfile1.txt
		cat sampleoutputs/outputfile1.txt
